name: Update Pie Chart

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Кожну неділю о 00:00 UTC

jobs:
  update-pie-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug Python Environment
        run: |
          echo "Installed Python Packages:"
          python -m pip list
          echo "Matplotlib Backend Test:"
          python -c "import matplotlib; print('Backend:', matplotlib.get_backend())"

      - name: Install Cairo for Matplotlib (if required)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev

      - name: Generate Pie Chart
        run: |
          python -c "import matplotlib; matplotlib.use('Agg')"
          python pie_generate_chart.py
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Verify Generated Files
        run: |
          if [ ! -f "pie_languages_chart.svg" ]; then 
            echo "Error: pie_languages_chart.svg not generated."; 
            exit 1; 
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pie_languages_chart.svg pie_language_colors.json
          git diff --cached --quiet || git commit -m "Update pie chart and color file"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
